# Generated by Django 2.2.16 on 2022-06-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220208_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'администратор'), ('moderator', 'Модератор'), ('user', 'Аутентифицированный пользователь')], default='user', max_length=50, verbose_name='Роль'),
        ),
    ]
